// This file is generated by openapi-typescript. Do not edit manually.
// Run: nx run api-types:codegen
//
// Placeholder — will be overwritten on codegen.
export type paths = Record<string, never>;
export type components = Record<string, never>;
